title = "Modern Caliber Hugo Test"

[params.author]
name = "Caleb Martin"
image = "img/logo.png"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://x.com/calebmartin634" }
]