backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment the following lines for local development (without Netlify)
# local_backend: true

site_url: https://moderncaliber-hugo.netlify.app/ # Update this with your actual Netlify site URL
display_url: https://moderncaliber-hugo.netlify.app/ # Update this with your actual Netlify site URL
logo_url: https://moderncaliber-hugo.netlify.app/logo.png

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
          label: 'Cover Image',
          name: 'featureimage',
          widget: 'image',
          required: false,
          hint: 'Upload a cover/featured image for this post',
        }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'list',
          default: ['Basics'],
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Show Author',
          name: 'showAuthor',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
